mob/Login()
	src.client.Set_Resolution()
	Center_Window(src,"Default")
	Center_Window(src,"Creation")
	Center_Window(src,"Selections")
	..()
proc/Window_Refresh(mob/M,Command,Output,Message)
	if(Command)
		winset(M,"[Output]","command=\"[Command]\"")
	M << output(null,"[Output]")
	M << output(Message,"[Output]")